name: Cypress Tests
on:
  schedule:
    # runs tests every day at 4am
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests daily 🌎 
        uses: cypress-io/github-actions@v5
        with:
          command: npm run all-tests

      - name: Upload cypress test artifacts 📦
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-test-artifacts
          path: cypress/videos
          retention-days: 30
