name: Cypress Tests
on:
  schedule:
    # runs tests every day at 4am
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  daily:
    name: e2e Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Cypress tests daily 🌎 
        uses: cypress-io/github-actions@v4
        with:
          command: npm run cy:run:qa:regression

      - name: Upload cypress test artifacts 📦
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-test-artifacts
          path: cypress/videos
          retention-days: 30
